// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCauKYFzkYaabuWy8X20Pgw2EF_dBKDgAs',
    appId: '1:118339255781:web:5f476b7f98667c9eaec30c',
    messagingSenderId: '118339255781',
    projectId: 'login-80c0a',
    authDomain: 'login-80c0a.firebaseapp.com',
    storageBucket: 'login-80c0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe7zkefM_Gk42wSxyS_O7_vtbUrGZlEDA',
    appId: '1:118339255781:android:8afe3ea6ab0a7ab9aec30c',
    messagingSenderId: '118339255781',
    projectId: 'login-80c0a',
    storageBucket: 'login-80c0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb1ZlB2CaOYQo2ZQFE5M2mm7HVXJersoc',
    appId: '1:118339255781:ios:2dc64eb33ff4335daec30c',
    messagingSenderId: '118339255781',
    projectId: 'login-80c0a',
    storageBucket: 'login-80c0a.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );
}
